require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails
  - rubocop-factory_bot
AllCops:
  NewCops: disable
Metrics/AbcSize:
  Enabled: false
Rails/BulkChangeTable:
  Enabled: false
Metrics/MethodLength:
  Max: 30
Metrics/BlockLength:
  Exclude:
    - 'config/environments/*'
RSpec/MultipleExpectations:
  Max: 2