require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails
  - rubocop-factory_bot
AllCops:
  NewCops: disable
Metrics/AbcSize:
  Max: 30
Metrics/MethodLength:
  Max: 30
RSpec/MultipleExpectations:
  Max: 2