default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>

development:
  <<: *default
  host: <%= ENV['DB_HOST'] %>
  database: <%= ENV['DATABASE'] %>

test:
  <<: *default
  host: <%= ENV['DB_HOST'] %>
  database: <%= ENV['DATABASE'] %>_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>