default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: storage/development.sqlite3
  username: postgres
  password: 123456

test:
  <<: *default
  database: storage/test.sqlite3
  username: postgres
  password: 123456

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>